/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.oocl.parkingsmart;

import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;

import static org.junit.jupiter.api.Assertions.assertNotNull;

@SpringBootTest
public class ParkingSmartBackendApplicationTests {

    @Test
    void contextLoads() {
    }

}
